### ISSUE TITLE
Cipherlab RS30 and my application crashes when I start initialise function

### ISSUE THREAD

**Issue by sebastianor** [mribbons/cordova-plugin-cipherlab-rs30#6]
When I'm trying run this code:
 `cordova.plugins.CipherlabRS30CordovaPlugin.initialise(function ()
 {
          cordova.plugins.CipherlabRS30CordovaPlugin.requestScan(function() 
           {
           });
          cordova.plugins.CipherlabRS30CordovaPlugin.setReceiveScanCallback(function (data) 
           {
                 console.log(data);
          });
        });`
My application unexpectedly crashes. Once in a while the application scans the code correctly. My cordova version is 6.2.0. In the image sending error log which could preview in the Eclipse. 
![zrzut ekranu 2016-06-04 o 22 19 00](https://cloud.githubusercontent.com/assets/11159141/15801861/9026aeea-2aa2-11e6-95a1-8fb5dc714a8c.png)

**Comment by mribbons** [comment]
Hi @sebastianor,
Your issue looks similar to #1 and #3 which were caused by the BarcodeAPI.jar file becoming out of date with the firmware of the target device.

Can you try to update them in your local repo of the plugin and see if that resolves.

You will need to overwrite this:
cordova-plugin-cipherlab-rs30/src/android/BarcodeAPI.jar

With the BarcodeAPI.jar that you have obtained from your Cipherlab supplier.

Currently the plugin supports BarcodeAPI_V1_0_35.jar

You might have an older version, you could also try this branch 
https://github.com/mribbons/cordova-plugin-cipherlab-rs30/tree/BarcodeAPI_v1.0.31

It really depends which version of the BarcodeAPI you have and know works with your device. You might also want to try updating your firmware, although I am unsure where to obtain updated firmware.

Just a note, if you want to provide logs from eclipse or other IDEs, please provide text version of the output. I know it's possible but I can't see any documentation.

Not sure about eclipse itself, but try this:
http://stackoverflow.com/a/2888222/3739540

adb shell logcat > log.txt

**Comment by sebastianor** [comment]
Ok. That works after install old version of BarcodeAPI.jar. Thanks for help.

**Comment by mribbons** [comment]
Thanks for getting back to me.
